# Importing Libraries

import pandas as pd
import numpy as np

#Importing Dataset

In [82]:
import pandas as pd
import numpy as np
data=pd.read_csv("weatherAUS.csv")
x=data.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]].values
y=data.iloc[:,-1].values

In [83]:
print(x)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 3.6 25.3 ... 10.9 24.5 'No']
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']]


In [84]:
print(y)

['No' 'No' 'No' ... 'No' 'No' 'No']


In [85]:
y=y.reshape(-1,1) #Used to convert 1D array/list into 2D

In [86]:
print(y)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 ['No']]


# Dealing with Invalid Dataset

In [87]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy="most_frequent")
x=imputer.fit_transform(x)
y=imputer.fit_transform(y)

In [88]:
print(x)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 3.6 25.3 ... 10.9 24.5 'No']
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']]


In [89]:
print(y)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 ['No']]


# Encoding Dataset

In [90]:
from sklearn.preprocessing import LabelEncoder
import warnings as wr
wr.filterwarnings("ignore")
le1 = LabelEncoder()
x[:,0] = le1.fit_transform(x[:,0])
le2 = LabelEncoder()
x[:,4] = le2.fit_transform(x[:,4])
le3 = LabelEncoder()
x[:,6] = le3.fit_transform(x[:,6])
le4 = LabelEncoder()
x[:,7] = le4.fit_transform(x[:,7])
le5 = LabelEncoder()
x[:,-1] = le5.fit_transform(x[:,-1])
le6 = LabelEncoder()
y = le6.fit_transform(y)

In [91]:
print(x)

[[2 13.4 22.9 ... 16.9 21.8 0]
 [2 7.4 25.1 ... 17.2 24.3 0]
 [2 12.9 25.7 ... 21.0 23.2 0]
 ...
 [41 3.6 25.3 ... 10.9 24.5 0]
 [41 5.4 26.9 ... 12.5 26.1 0]
 [41 7.8 27.0 ... 15.1 26.0 0]]


In [92]:
print(y)

[0 0 0 ... 0 0 0]


# Feature scaling

In [93]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

In [94]:
print(x)

[[-1.5270045   0.19169797 -0.044926   ... -0.01353307  0.02110819
  -0.53296232]
 [-1.5270045  -0.74708764  0.26444584 ...  0.03281942  0.38476354
  -0.53296232]
 [-1.5270045   0.11346584  0.34881998 ...  0.61995105  0.22475519
  -0.53296232]
 ...
 [ 1.21224943 -1.34165186  0.29257055 ... -0.94058301  0.41385597
  -0.53296232]
 [ 1.21224943 -1.06001618  0.51756825 ... -0.69336969  0.64659539
  -0.53296232]
 [ 1.21224943 -0.68450193  0.53163061 ... -0.29164805  0.63204918
  -0.53296232]]


# Spliting Dataset into Training set and Test set

In [95]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [96]:
print(x_train)

[[ 1.56343583  0.26993011 -0.08711307 ...  0.28003274 -0.18253881
  -0.53296232]
 [-1.10558082  1.59987639  0.86912716 ...  1.45429598  0.85024239
   1.87630525]
 [-1.45676722 -0.38721982  1.82536739 ...  1.77876346  1.94120845
  -0.53296232]
 ...
 [-1.66747906 -0.04299843 -0.79023088 ... -0.38435305 -0.66256387
   1.87630525]
 [ 0.50987663 -0.70014836  0.39100704 ... -0.39980388  0.42840218
  -0.53296232]
 [ 1.63367311  1.22436215  1.16443664 ...  1.40794349  0.16657033
  -0.53296232]]


In [97]:
print(y_train)

[0 0 0 ... 0 0 1]


# Training Model

In [98]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=100,random_state=0)
classifier.fit(x_train,y_train)

RandomForestClassifier(random_state=0)

In [99]:
classifier.score(x_train,y_train)

0.999920881903054

In [100]:
print(y_test)

[0 0 0 ... 0 0 1]


In [101]:
y_pred=classifier.predict(x_test)

In [102]:
print(y_pred)

[0 0 0 ... 0 0 1]


In [ ]:
#convert values of 0/1 to yes/no

In [104]:
y_pred=le6.inverse_transform(y_pred)
print(y_pred)

['No' 'No' 'No' ... 'No' 'No' 'Yes']


In [105]:
y_test=le6.inverse_transform(y_test)
print(y_test)

['No' 'No' 'No' ... 'No' 'No' 'Yes']


# Convert data from 1D to 2D form

In [106]:
y_pred=y_pred.reshape(-1,1)
y_test=y_test.reshape(-1,1)

# Concat test & pred data and creat dataframe

In [107]:
df=np.concatenate((y_test,y_pred),axis=1)
dataframe=pd.DataFrame(df,columns=["Rain on Tommorrow","Prediction of Rain"])
print(df)

[['No' 'No']
 ['No' 'No']
 ['No' 'No']
 ...
 ['No' 'No']
 ['No' 'No']
 ['Yes' 'Yes']]


In [108]:
print(dataframe)

      Rain on Tommorrow Prediction of Rain
0                    No                 No
1                    No                 No
2                    No                 No
3                    No                 No
4                    No                 No
5                    No                 No
6                   Yes                Yes
7                   Yes                Yes
8                    No                 No
9                    No                 No
10                   No                 No
11                   No                 No
12                   No                 No
13                   No                 No
14                  Yes                Yes
15                   No                 No
16                   No                 No
17                   No                 No
18                   No                 No
19                   No                 No
20                   No                 No
21                   No                 No
22         

# Calculating Accuracy

In [109]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8569218326945391

# Creating File of dataframe

In [110]:
dataframe.to_csv('prediction_by_model.csv')